[project]
name = "eccom-prod-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [langchain  ]

[tool.setuptools.packages.find]
include = ["prod_assistant"]
